version: '2.7'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: 'php ../../bin/roadrunner-worker.php'

http:
  address: '0.0.0.0:8080'
  middleware: ['static']
  static:
    dir: '../../public'
    forbid: ['.php', '.htaccess']
  pool:
    num_workers: 16

jobs:
  pool:
    num_workers: 16
  timeout: 300
  consume: ['shlink']
  pipelines:
    shlink:
      driver: memory
      config:
        priority: 10
        prefetch: 10

logs:
  mode: development
  channels:
    http:
      level: debug
    server:
      level: debug
    metrics:
      level: debug

reload:
  interval: 1s
  patterns: ['.php']
  services:
    http:
      dirs: ['../../bin', '../../config', '../../data/migrations', '../../module', '../../vendor']
      recursive: true
    jobs:
      dirs: ['../../bin', '../../config', '../../data/migrations', '../../module', '../../vendor']
      recursive: true
